import { motion } from 'framer-motion'
import type { NextPage } from "next";
import Head from "next/head";
import Layout from '../components/Layouts/Article';
import Main from "../components/Layouts/Main";
import Who from "../components/Who";

const variants = {
  hidden: { opacity: 0, x: 0, y: 20 },
  enter: { opacity: 1, x: 0, y: 0 },
  exit: { opacity: 0, x: -0, y: 20 }
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ZACHURI | DEV
        </title>
        <meta name="Zachary Punsalng Portfolio" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Layout>
        <Who />
      </Layout>
    </>
  );
};

export default Home;

