import type { NextPage } from 'next';
import { NextSeo } from 'next-seo';
import Head from 'next/head';
import LayoutMotion from '../components/Layouts/Motion';
import Who from '../components/Who';

const url = 'https://zachuri.com';
const title = 'Home';
const description =
  'Hello, I&apos;m a Web Developer based in Irvine, California! Zachary Punsalang. Developer (Web, Application, Game)`';

const Home: NextPage = () => {
  return (
    <>
      <NextSeo
        title={title}
        description={description}
        canonical={url}
        openGraph={{ url, title, description }}
      />
      <Head>
        <title>ZACHURI | Home</title>
        <meta
          name="Zachary Punsalng Portfolio"
          content="Generated by create-t3-app"
        />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/logo.png" />
      </Head>

      <LayoutMotion>
        <Who />
      </LayoutMotion>
    </>
  );
};

export default Home;
